### ISSUE TITLE
Dollar symbol not being rendered on Android HTC One M9 phone

### ISSUE THREAD

**Issue by yawaramin** [telusdigital/tds-core#514] opened 2018-03-08 20:17 UTC
## Description

* A plain text dollar symbol ($) is not being rendered inside a TDS React component (Radio). Instead, another symbol (a circle with four strokes on it) is rendered.

## Reproduction Steps

* Get an HTC One M9 phone (there's on in the QA device cabinet cc Ben Chen)
* Log in as a user eligible for payment arrangement
* Go to payment arrangement page
* Check dollar amounts

## Reproduction Percentage (if applicable)

* always, also repro'd by @amelcharai in Billing page

## Meta

* TDS version: v1.0.3
* Willing to develop solution: Yes
* Has workaround: No
* High impact: No

## Screenshots

* ![screenshot_2018-03-08-14-39-29](https://user-images.githubusercontent.com/6997/37174152-bd30f644-22e3-11e8-9f34-50ea60e4df30.png)

**Comment by Nintendot** [comment] 2018-03-08 22:14
To my understanding issues are normally not associated with a particular device, but platform version / browser version / view port. Are you able to get those and reproduce on a emulator / device with same environment?

**Comment by ryanoglesby08** [comment] 2018-03-09 15:11
@yawaramin 

> A plain text dollar symbol ($) is not being rendered inside a TDS React component (Radio)

My assumption here is that this oddity is not specific to the `Radio` component. Does the same thing happen outside of that component?

I'm also assuming that this must have something to do with the web font, and not really specific to any TDS components. Do you see the same behaviour if you take TDS, and React for that matter, out of the equation?

Here is a simple HTML page to test with that only loads the TELUS Web font face:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Test dollar sign</title>
  <style>
@font-face {
  font-family: 'TELUS-Web';
  font-style: normal;
  font-weight: 400;
  src: url('https://cdn.telus.digital/thorium/core/fonts/etext/b8765d4b-d9a3-48b9-ac65-560e7517cf0e.woff2')
      format('woff2'),
    url('https://cdn.telus.digital/thorium/core/fonts/etext/d7d2e6c6-fc3a-41a5-9b52-648e12e215b2.woff')
      format('woff'),
    url('https://cdn.telus.digital/thorium/core/fonts/etext/cb64744b-d0f7-4ef8-a790-b60d6e3e4f21.ttf')
      format('truetype'),
    url('https://cdn.telus.digital/thorium/core/fonts/etext/e0781a75-0ecb-464e-b6e9-85780ddc0921.eot?#iefix')
      format('eot');
}

body {
  font-family: 'TELUS-Web';
  font-weight: 400;
}
  </style>
</head>
<body>
  <div>Here is the dollar sign: $</div>
</body>
</html>
```

**Comment by yawaramin** [comment] 2018-03-09 15:39
Thanks Ryan for the simplified test case. I'll retrieve that phone and check on Monday.

@Nintendot thanks Ben, I'll also add those details here on Monday.

**Comment by ryanoglesby08** [comment] 2018-04-03 16:43
@yawaramin any more info here? Is this still an issue? Unless we can pinpoint something in TDS as the culprit here we will probably close this one.

**Comment by Nintendot** [comment] 2018-04-03 17:27
@ryanoglesby08 I believe Yawar has move on from Digital, his team is sharing the responsibility for testing currently. Not sure if they are aware of this though.
cc: @SteveTelus

**Comment by theetrain** [comment] 2018-05-16 17:15
Closing due to inactivity. Feel free to add a comment if this is still needed.

**Closed by theetrain** 2018-05-16 17:15 UTC
